name: @@NAME@@
version: @@VERSION@@
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

architectures:
  - build-on: amd64
    run-on: @@ARCHITECTURE@@
compression: lzo

grade: stable
confinement: classic
base: core18

parts:
  code:
    plugin: dump
    source: .
    stage-packages:
      - ibus-gtk3
      - fcitx-frontend-gtk3
      - gvfs-libs
      - libasound2
      - libgconf-2-4
      - libglib2.0-bin
      - libgnome-keyring0
      - libgbm1
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libsecret-1-0
      - libxss1
      - libxtst6
      - zlib1g
      - libxshmfence1
    prime:
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
  gnome-platform:
    plugin: nil
    build-packages:
      - snapd
    override-pull: |
      set -eu
      snap download gnome-3-34-1804 --edge
      unsquashfs gnome-*.snap
    override-build: |
      set -eu
      [ -d squashfs-root/ ] || exit 1
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
      cp -a squashfs-root/* $SNAPCRAFT_PART_INSTALL/gnome-platform
  gnome-3-34-extension:
    after:
      - gnome-platform
    build-packages:
      - gcc
    build-snaps:
      - gnome-3-34-1804-sdk/latest/stable
    make-parameters:
      - WITH_BINDTEXTDOMAIN=1
      - PLATFORM_PLUG=gnome-3-34-1804
    plugin: make
    source: $SNAPCRAFT_EXTENSIONS_DIR/desktop
    source-subdir: gnome
    override-stage: |
      snapcraftctl stage
      tail -n +2 $SNAPCRAFT_PART_INSTALL/snap/command-chain/desktop-launch | sed -e "/if ! snapctl is-connected/,/fi/d" > $SNAPCRAFT_PART_INSTALL/snap/command-chain/desktop-launch
  electron-launch-wrapper:
    source: .
    plugin: dump
    after:
      - code
    organize:
      electron-launch : bin/electron-launch

apps:
  @@NAME@@:
    command: bin/electron-launch $SNAP/usr/share/@@NAME@@/bin/@@NAME@@ --no-sandbox
    common-id: @@NAME@@.desktop
    command-chain:
      - snap/command-chain/desktop-launch
    environment:
      GTK_USE_PORTAL: 1
      DISABLE_WAYLAND: 1
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform

  url-handler:
    command: bin/electron-launch $SNAP/usr/share/@@NAME@@/bin/@@NAME@@ --open-url --no-sandbox
    command-chain:
      - snap/command-chain/desktop-launch
    environment:
      GTK_USE_PORTAL: 1
      DISABLE_WAYLAND: 1
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform

hooks:
  configure:
    command-chain:
      - snap/command-chain/hooks-configure-desktop

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
